# generated by datamodel-codegen:
#   filename:  simulation.json
#   timestamp: 2020-10-13T11:35:35+00:00

from datetime import date
from pydantic import BaseModel, Field


class Simulation(BaseModel):
    init_date: date = Field(..., title='Initial date')
    end_date: date = Field(..., title='End date')
    name: str = Field(..., title='Simulation name')
    id: str = Field(..., title='Simlation ID')
    code: int = Field(..., title='Simulation code')
